
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace DianDianClient.Models
{

using System;
    using System.Collections.Generic;
    
public partial class dd_user
{

    public int id { get; set; }

    public Nullable<int> userid { get; set; }

    public string username { get; set; }

    public string password { get; set; }

    public Nullable<int> shopid { get; set; }

    public Nullable<int> autoconfirm { get; set; }

    public string token { get; set; }

    public string dprinter { get; set; }

    public string dcomm { get; set; }

    public Nullable<int> isfirst { get; set; }

}

}
