
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace DianDianClient.Models
{

using System;
    using System.Collections.Generic;
    
public partial class shop_edit
{

    public int shopkey { get; set; }

    public string shopCode { get; set; }

    public string name { get; set; }

    public Nullable<int> shopType { get; set; }

    public string thumb { get; set; }

    public Nullable<int> place { get; set; }

    public string introduce { get; set; }

    public string phone { get; set; }

    public string detailAddr { get; set; }

    public Nullable<int> orderNo { get; set; }

    public Nullable<int> isDel { get; set; }

    public string openAccountBank { get; set; }

    public string bankNo { get; set; }

    public string bankRealName { get; set; }

    public Nullable<int> isPrint { get; set; }

    public string printer { get; set; }

    public Nullable<int> autoRecvOrder { get; set; }

    public Nullable<int> autoPrint { get; set; }

    public Nullable<int> isAudit { get; set; }

    public string contact { get; set; }

    public Nullable<System.DateTime> createDate { get; set; }

    public string qrCode { get; set; }

    public Nullable<int> islocktable { get; set; }

    public Nullable<int> isposition { get; set; }

    public string bgimg { get; set; }

    public string tastes { get; set; }

    public string longitude { get; set; }

    public string province { get; set; }

    public string city { get; set; }

    public string district { get; set; }

    public string street { get; set; }

    public string address { get; set; }

    public Nullable<decimal> averageprice { get; set; }

    public string signatory { get; set; }

    public string fixer { get; set; }

    public string latitude { get; set; }

    public string banktype { get; set; }

    public string managetype { get; set; }

    public Nullable<decimal> signrate { get; set; }

    public Nullable<decimal> t0rate { get; set; }

    public Nullable<decimal> cardrate { get; set; }

    public Nullable<int> validitydate { get; set; }

    public string license { get; set; }

    public string character { get; set; }

    public string licenseaddr { get; set; }

    public string licupdatedate { get; set; }

    public string asdate { get; set; }

    public string legaler { get; set; }

    public string legaleridcard { get; set; }

    public string legaleridvalidity { get; set; }

    public string legalerphone { get; set; }

    public Nullable<int> agentid { get; set; }

    public string bankcode { get; set; }

    public string bankname { get; set; }

    public string chaintype { get; set; }

    public Nullable<sbyte> ist0 { get; set; }

    public string creditcardno { get; set; }

    public Nullable<decimal> quickrate { get; set; }

    public Nullable<sbyte> isserver { get; set; }

    public string zbankname { get; set; }

    public string zbankcode { get; set; }

}

}
