
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace DianDianClient.Models
{

using System;
    using System.Collections.Generic;
    
public partial class v_category_items
{

    public int itemcategorymapkey { get; set; }

    public Nullable<int> itemkey { get; set; }

    public Nullable<int> itemcategorykey { get; set; }

    public Nullable<int> index { get; set; }

    public Nullable<int> shopkey { get; set; }

    public string itemCategoryCode { get; set; }

    public string categoryName { get; set; }

    public string instructions { get; set; }

    public string categoryImg { get; set; }

    public Nullable<int> enable { get; set; }

    public Nullable<int> categoryOrderNo { get; set; }

    public Nullable<int> categoryIsDel { get; set; }

    public string itemCode { get; set; }

    public Nullable<int> itemType { get; set; }

    public string itemName { get; set; }

    public string introduce { get; set; }

    public string thumb { get; set; }

    public Nullable<int> place { get; set; }

    public string itemImgs { get; set; }

    public Nullable<double> price { get; set; }

    public Nullable<double> discountPrice { get; set; }

    public Nullable<double> discount { get; set; }

    public Nullable<int> stockNum { get; set; }

    public Nullable<int> soldNum { get; set; }

    public string unit { get; set; }

    public Nullable<System.DateTime> createDate { get; set; }

    public Nullable<int> state { get; set; }

    public Nullable<int> itemOrderNo { get; set; }

    public Nullable<int> isShowIndex { get; set; }

    public Nullable<int> itemIsDel { get; set; }

    public Nullable<int> recommentNum { get; set; }

    public Nullable<System.DateTime> commentDate { get; set; }

    public Nullable<int> isSet { get; set; }

    public Nullable<int> isStandard { get; set; }

    public Nullable<double> agioprice { get; set; }

    public Nullable<int> minnum { get; set; }

    public Nullable<int> islikenum { get; set; }

    public Nullable<int> unlikenum { get; set; }

    public Nullable<int> isprint { get; set; }

    public Nullable<int> isprintset { get; set; }

    public Nullable<int> storagenum { get; set; }

    public Nullable<sbyte> selebyunit { get; set; }

    public Nullable<sbyte> ispayagio { get; set; }

    public Nullable<sbyte> ismust { get; set; }

    public Nullable<sbyte> isware { get; set; }

}

}
