//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_cfmainaccount
    {
        public string cfmainkey { get; set; }
        public string cfmealkey { get; set; }
        public Nullable<int> main_type { get; set; }
        public string billNo { get; set; }
        public Nullable<int> peopleNum { get; set; }
        public string scTime { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<decimal> realPay { get; set; }
        public Nullable<int> memberkey { get; set; }
        public string remark { get; set; }
        public string customRemark { get; set; }
        public Nullable<System.DateTime> payDate { get; set; }
        public Nullable<int> state { get; set; }
        public int tableNo { get; set; }
        public string orderNo { get; set; }
        public Nullable<int> main_payType { get; set; }
        public string introduce { get; set; }
        public Nullable<int> isConfirm { get; set; }
        public string exceptionPlan { get; set; }
        public string exceptionRemark { get; set; }
        public Nullable<System.DateTime> exceptionTime { get; set; }
        public Nullable<int> isComplete { get; set; }
        public Nullable<int> isSong { get; set; }
        public Nullable<int> isException { get; set; }
        public Nullable<double> youhui { get; set; }
        public Nullable<double> exceptionAmount { get; set; }
        public Nullable<double> exceptionAmountUn { get; set; }
        public Nullable<double> exceptionAmountAl { get; set; }
        public Nullable<int> serialNo { get; set; }
        public Nullable<decimal> zexception { get; set; }
        public int saccountid { get; set; }
        public Nullable<int> shopkey { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<decimal> brokerage { get; set; }
        public Nullable<decimal> rate { get; set; }
        public string ratetype { get; set; }
        public string isxingye { get; set; }
        public string type { get; set; }
        public string isonline { get; set; }
        public string issao { get; set; }
        public Nullable<int> paytype { get; set; }
        public Nullable<bool> isdian { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> puserid { get; set; }
        public Nullable<bool> isrong { get; set; }
        public Nullable<bool> ist0 { get; set; }
        public Nullable<decimal> fmoney { get; set; }
        public Nullable<bool> isact { get; set; }
        public Nullable<int> cashier { get; set; }
        public Nullable<int> waiter { get; set; }
        public Nullable<bool> iskuai { get; set; }
        public Nullable<bool> issever { get; set; }
        public Nullable<sbyte> cardtype { get; set; }
        public Nullable<int> chaneltype { get; set; }
        public string payway { get; set; }
    }
}
