//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_cfmainmeal
    {
        public string cfmainkey { get; set; }
        public string cfmealkey { get; set; }
        public Nullable<int> type { get; set; }
        public string billNo { get; set; }
        public Nullable<int> shopkey { get; set; }
        public Nullable<int> peopleNum { get; set; }
        public string scTime { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<decimal> realPay { get; set; }
        public Nullable<int> memberkey { get; set; }
        public string remark { get; set; }
        public string customRemark { get; set; }
        public string main_createDate { get; set; }
        public string payDate { get; set; }
        public Nullable<int> state { get; set; }
        public int tableNo { get; set; }
        public string orderNo { get; set; }
        public string introduce { get; set; }
        public Nullable<int> isConfirm { get; set; }
        public string exceptionPlan { get; set; }
        public string exceptionRemark { get; set; }
        public string exceptionTime { get; set; }
        public Nullable<int> main_isComplete { get; set; }
        public Nullable<int> isSong { get; set; }
        public Nullable<int> isException { get; set; }
        public Nullable<double> youhui { get; set; }
        public Nullable<double> exceptionAmount { get; set; }
        public Nullable<double> exceptionAmountUn { get; set; }
        public Nullable<double> exceptionAmountAl { get; set; }
        public Nullable<int> serialNo { get; set; }
        public Nullable<decimal> zexception { get; set; }
        public string createDate { get; set; }
        public Nullable<int> isComplete { get; set; }
        public Nullable<int> isRecomment { get; set; }
        public string main_serialNo { get; set; }
        public string redPackageCode { get; set; }
        public string main_exceptionPlan { get; set; }
        public string main_exceptionRemark { get; set; }
        public string payMemberkey { get; set; }
        public string recommentMemberkey { get; set; }
        public string useHbCode { get; set; }
        public string jiucanno { get; set; }
        public string merge { get; set; }
        public Nullable<int> peoples { get; set; }
        public Nullable<bool> isfree { get; set; }
        public Nullable<bool> issign { get; set; }
        public Nullable<int> shopuserid { get; set; }
        public Nullable<int> payType { get; set; }
    }
}
