//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_cfdetailitem
    {
        public string cfdetailkey { get; set; }
        public string cfmainkey { get; set; }
        public Nullable<int> memberkey { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<int> itemkey { get; set; }
        public Nullable<int> type { get; set; }
        public string createDate { get; set; }
        public string completeDate { get; set; }
        public Nullable<int> isComplete { get; set; }
        public Nullable<int> mgrkey { get; set; }
        public Nullable<int> interactionrecordkey1 { get; set; }
        public Nullable<int> interactionrecordkey2 { get; set; }
        public Nullable<int> isSong { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> isException { get; set; }
        public string exceptionRemark { get; set; }
        public Nullable<int> excptionNum { get; set; }
        public Nullable<int> guigeid { get; set; }
        public string guigename { get; set; }
        public string exceptionRemarkStr { get; set; }
        public string zuofa { get; set; }
        public string songcaiyuanyin { get; set; }
        public Nullable<decimal> youhui { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string itemCode { get; set; }
        public Nullable<int> itemType { get; set; }
        public Nullable<int> itemcategorykey { get; set; }
        public Nullable<int> shopkey { get; set; }
        public string name { get; set; }
        public string introduce { get; set; }
        public string thumb { get; set; }
        public Nullable<int> place { get; set; }
        public string imgs { get; set; }
        public Nullable<double> item_price { get; set; }
        public Nullable<double> discountPrice { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<int> stockNum { get; set; }
        public Nullable<int> soldNum { get; set; }
        public string unit { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> orderNo { get; set; }
        public Nullable<int> isShowIndex { get; set; }
        public Nullable<int> isDel { get; set; }
        public Nullable<int> recommentNum { get; set; }
        public Nullable<System.DateTime> commentDate { get; set; }
        public Nullable<int> isSet { get; set; }
        public Nullable<int> isStandard { get; set; }
        public Nullable<double> agioprice { get; set; }
        public Nullable<int> minnum { get; set; }
        public Nullable<int> islikenum { get; set; }
        public Nullable<int> unlikenum { get; set; }
        public Nullable<int> isprint { get; set; }
        public Nullable<int> isprintset { get; set; }
        public Nullable<int> storagenum { get; set; }
        public Nullable<sbyte> selebyunit { get; set; }
        public Nullable<sbyte> ispayagio { get; set; }
        public Nullable<sbyte> ismust { get; set; }
        public Nullable<sbyte> isware { get; set; }
    }
}
