//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_depotout_crude
    {
        public Nullable<int> depotoutid { get; set; }
        public Nullable<int> crudeid { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<decimal> salemoney { get; set; }
        public Nullable<int> shopkey { get; set; }
        public Nullable<int> surplus { get; set; }
        public string crudename { get; set; }
        public string unit { get; set; }
        public string standard { get; set; }
        public string crudecode { get; set; }
        public string barcode { get; set; }
        public Nullable<int> genreid { get; set; }
        public Nullable<sbyte> state { get; set; }
        public Nullable<int> depotid { get; set; }
        public string dutyperson { get; set; }
        public Nullable<int> itemkey { get; set; }
        public Nullable<decimal> depinout_salemoney { get; set; }
        public Nullable<sbyte> type { get; set; }
        public int outinfoid { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string categoryName { get; set; }
        public string itemName { get; set; }
    }
}
