//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_mem_card_shop
    {
        public Nullable<int> shopkey { get; set; }
        public string name { get; set; }
        public int cardid { get; set; }
        public string cardno { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> suserid { get; set; }
        public Nullable<decimal> money { get; set; }
        public string telno { get; set; }
        public string realname { get; set; }
        public Nullable<int> isvalid { get; set; }
        public Nullable<int> expirydate { get; set; }
        public Nullable<int> addtime { get; set; }
        public Nullable<int> jifen { get; set; }
    }
}
