
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace DianDianClient.Models
{

using System;
    using System.Collections.Generic;
    
public partial class v_memberrole
{

    public int memberkey { get; set; }

    public Nullable<int> shopkey { get; set; }

    public Nullable<int> postkey { get; set; }

    public Nullable<int> memberLevel { get; set; }

    public Nullable<int> type { get; set; }

    public string name { get; set; }

    public string loginName { get; set; }

    public string pwd { get; set; }

    public string secpwd { get; set; }

    public string icon { get; set; }

    public string tel { get; set; }

    public string email { get; set; }

    public Nullable<int> score { get; set; }

    public Nullable<double> balance { get; set; }

    public string WebSite1Uid { get; set; }

    public string WebSite2Uid { get; set; }

    public string WebSite3Uid { get; set; }

    public Nullable<int> enable { get; set; }

    public Nullable<System.DateTime> createDate { get; set; }

    public Nullable<int> provinceId { get; set; }

    public Nullable<int> cityId { get; set; }

    public Nullable<int> areaId { get; set; }

    public string code { get; set; }

    public Nullable<int> parentMemberkey { get; set; }

    public Nullable<int> isDel { get; set; }

    public string token { get; set; }

    public decimal lat { get; set; }

    public decimal lng { get; set; }

    public Nullable<int> agentid { get; set; }

    public Nullable<long> superroleid { get; set; }

    public string rolename { get; set; }

    public string descb { get; set; }

    public string rtype { get; set; }

    public Nullable<long> sysroleid { get; set; }

}

}
